### ISSUE TITLE
error in 07_build_pastix_kabbone.sh on Archlinux

### ISSUE THREAD

**Issue by QiangF** [rsmith-nl/calculix-build-pastix#1]
I have solved many errors in the previous steps, but this one:

    CMake Error at test/CMakeLists.txt:43 (add_library):
      No SOURCES given to target: bcsc_test
    
    
    CMake Error at test/CMakeLists.txt:122 (add_library):
      No SOURCES given to target: pastix_tests
    
    
    CMake Generate step failed.  Build files cannot be regenerated correctly.
    q@mypc:calculix-build-pastix$ ./07_build_pastix_kabbone.sh > build.log
    CMake Error at test/CMakeLists.txt:43 (add_library):
      No SOURCES given to target: bcsc_test
    
    
    CMake Error at test/CMakeLists.txt:122 (add_library):
      No SOURCES given to target: pastix_tests
    
    
    CMake Generate step failed.  Build files cannot be regenerated correctly.
    
The command output is here:
https://gist.github.com/QiangF/2d47eb34f6ecc934a8a05c0fb7001a45

**Comment by QiangF** [comment]
More errors:

    -- Configuring done (3.1s)
    -- Generating done (0.1s)
    -- Build files have been written to: /tmp/my_cache/calculix-build-pastix/source/pastix4calculix/build
    [  1%] Built target sopalin_headers
    [  1%] Built target bcsc_headers_tgt
    [  1%] Built target parsec_headers_tgt
    [  1%] Building C object kernels/CMakeFiles/pastix_kernels.dir/lowrank.c.o
    [  1%] Building C object kernels/CMakeFiles/pastix_kernels.dir/kernels_trace.c.o
    [  1%] Built target spm_headers_tgt
    [  1%] Built target kernels_headers_tgt
    [  1%] Built target tests_headers_tgt
    [  1%] Built target refinement_headers_tgt
    [  2%] Building C object spm/CMakeFiles/spm.dir/src/spm.c.o
    [  2%] Building C object spm/CMakeFiles/spm.dir/src/spm_io.c.o
    /tmp/my_cache/calculix-build-pastix/source/pastix4calculix/kernels/lowrank.c:19:10: fatal error: pastix_clrcores.h: No such file or directory
       19 | #include "pastix_clrcores.h"
          |          ^~~~~~~~~~~~~~~~~~~
    compilation terminated.
    gmake[2]: *** [kernels/CMakeFiles/pastix_kernels.dir/build.make:76: kernels/CMakeFiles/pastix_kernels.dir/lowrank.c.o] Error 1
    gmake[2]: *** Waiting for unfinished jobs....
    [  3%] Building C object spm/CMakeFiles/spm.dir/src/spm_integers.c.o
    gmake[1]: *** [CMakeFiles/Makefile2:1464: kernels/CMakeFiles/pastix_kernels.dir/all] Error 2
    gmake[1]: *** Waiting for unfinished jobs....
    [  4%] Building C object spm/CMakeFiles/spm.dir/src/spm_dof_extend.c.o
    /tmp/my_cache/calculix-build-pastix/source/pastix4calculix/spm/src/spm.c:22:10: fatal error: c_spm.h: No such file or directory
       22 | #include "c_spm.h"
          |          ^~~~~~~~~
    compilation terminated.
    gmake[2]: *** [spm/CMakeFiles/spm.dir/build.make:76: spm/CMakeFiles/spm.dir/src/spm.c.o] Error 1
    gmake[2]: *** Waiting for unfinished jobs....
    /tmp/my_cache/calculix-build-pastix/source/pastix4calculix/spm/src/spm_dof_extend.c:20:10: fatal error: c_spm.h: No such file or directory
       20 | #include "c_spm.h"
          |          ^~~~~~~~~
    compilation terminated.
    gmake[2]: *** [spm/CMakeFiles/spm.dir/build.make:118: spm/CMakeFiles/spm.dir/src/spm_dof_extend.c.o] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:1224: spm/CMakeFiles/spm.dir/all] Error 2
    gmake: *** [Makefile:146: all] Error 2

**Comment by rsmith-nl** [comment]
Are you running the build scripts in the correct order?

Also, all the previous build scripts have to finish without errors before you can proceed to the next.

**Comment by QiangF** [comment]
I tried one more time with the updated code, I have to skip 04_build_hwloc, because it will make 05_build_parsec fail. I got “No SOURCES given to target: bcsc_test“, here is the command output: https://gist.github.com/QiangF/f3a1207be7e39cd134f8bebd276b710c

**Comment by rsmith-nl** [comment]
It is now using the intel MKL math libraries. This is not a configuration I can test, because these aren't available for FreeBSD.

The only configuration I have tested is with all the built scripts run in order and completing with without errors.

**Comment by sim-saurabh** [comment]
This (missing header files pastix_clrcores.h and c_spm.h) is the exact issue we're having. It has nothing to do with 04_build_hwloc.sh which we did run. It likely has nothing to do with 05_build_parsec.h too since that file is not even there anymore in the tarball. Those files are included in the kabbone source but they're missing from the kabbone tarball. It looks like the distro is incomplete/inconsistent.
