### ISSUE TITLE
config error in 04_build_hwloc.sh

### ISSUE THREAD

**Issue by QiangF** [rsmith-nl/calculix-build-pastix#2]
###
     ### Configuring hwloc distribution tarball
     ### Startup tests
     ###
     checking build system type... x86_64-pc-linux-gnu
     checking host system type... x86_64-pc-linux-gnu
     checking target system type... x86_64-pc-linux-gnu
     checking for a BSD-compatible install... /usr/bin/install -c
     checking whether build environment is sane... yes
     checking for a race-free mkdir -p... /usr/bin/mkdir -p
     checking for gawk... gawk
     checking whether make sets $(MAKE)... yes
     checking whether make supports nested variables... yes
     checking whether UID '1000' is supported by ustar format... yes
     checking whether GID '998' is supported by ustar format... yes
     checking how to create a ustar tar archive... gnutar
     checking whether make supports nested variables... (cached) yes
     checking whether make supports the include directive... yes (GNU style)
     checking for gcc... gcc13
     checking whether the C compiler works... no
     configure: error: in `/tmp/my_cache/calculix-build-pastix/source/hwloc':
     configure: error: C compiler cannot create executables
     See `config.log' for more details
     
config.log is here https://gist.github.com/QiangF/f2fab74e00614a246b877ba34ee1ac13

**Comment by rsmith-nl** [comment]
> configure:5117: gcc13    conftest.c -lexecinfo -lpciaccess >&5
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/13.3.0/../../../../lib/libexecinfo.so: undefined reference to `log10'

Apparently, libexecinfo requires the math library on Linux.

In the script, change LIBS to:
`LIBS='-lexecinfo -lm -lpciaccess'`

**Comment by rsmith-nl** [comment]
Update has been pushed to the repo.
