### ISSUE TITLE
error in 05_build_parsec.sh on archlinux

### ISSUE THREAD

**Issue by QiangF** [rsmith-nl/calculix-build-pastix#3]
This error happens after the successful build of hwloc. On my previous try, because hwloc fails to build, I installed hwloc from the arch repo, and 05_build_parsec.sh complete without errors.
The build command output is here https://gist.github.com/QiangF/4ea5351e73a83e40b46bcc9d4c3b7728

**Comment by rsmith-nl** [comment]
The hwloc you're using is built with X11/OpenGL. You will have to add the required libraries to the `-DEXTRA_LIBS` of cmake in `05_build_parsec.sh`.
